name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: borales/actions-yarn@v3
      with:
        cmd: install --frozen-lockfile

    - name: Build
      uses: borales/actions-yarn@v3
      with:
        cmd: build

    - name: Install Firebird
      run: |
        sudo apt-get install libtommath1 libncurses5
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libtommath.so.1 /usr/lib/x86_64-linux-gnu/libtommath.so.0
        wget -nv -O Firebird-3.0.10.33601-0.amd64.tar.gz "https://github.com/FirebirdSQL/firebird/releases/download/v3.0.10/Firebird-3.0.10.33601-0.amd64.tar.gz"
        tar xzvf Firebird-3.0.10.33601-0.amd64.tar.gz
        (cd Firebird-3.0.10.33601-0.amd64; sudo ./install.sh -silent)
        sudo usermod -a -G firebird `whoami`
        echo 'WireCrypt = Enabled' | sudo tee -a /opt/firebird/firebird.conf > /dev/null
        sudo killall firebird
        sudo systemctl start firebird-superserver.service
        sudo chown root:firebird /opt/firebird/SYSDBA.password
        sudo chmod 440 /opt/firebird/SYSDBA.password
        sudo chown -R firebird:firebird .
        while ! nc -z localhost 3050; do sleep 1 ; done
        sleep 2

    - name: Tests
      run: |
        sudo mkdir coverage
        sudo chown -R firebird:firebird coverage
        sudo chmod -R 777 coverage
        sg firebird -c "yarn global add env-cmd; env-cmd -f /opt/firebird/SYSDBA.password yarn test"
        bash <(curl -s https://codecov.io/bash)
